{% set version = "0.2.0" %}
{% set js_version = version.replace('a', '-alpha').replace('b', '-beta') %}

package:
  name: ipyforcegraph
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyforcegraph/ipyforcegraph-{{ version }}.tar.gz
  sha256: 7679bf7b167b5321a14d1b5d6987259893dcba5556bebc70d36138b58e5154f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - flit-core >=3.7.1,<4
    - pip
    - python >=3.8
  run:
    - ipywidgets >=8.0.4,<9
    - numcodecs
    - pandas
    - python >=3.8
    - traittypes
  run_constrained:
    - jupyterlab >=3.0

test:
  imports:
    - ipyforcegraph

  commands:
    - python -m pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@jupyrdf/jupyter-forcegraph.*v{{ js_version }}.*OK" labextensions
  requires:
    - jupyterlab
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/jupyrdf/ipyforcegraph
  summary: 2D and 3D force-directed graph widgets for Jupyter
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - src/_d/share/jupyter/labextensions/@jupyrdf/jupyter-forcegraph/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
